<Project>
  <PropertyGroup>
    <GalleryAppName>DevWinUI.Gallery</GalleryAppName>
    <ContextMenuLibName>DevWinUI.ContextMenu</ContextMenuLibName>
    <BaseNamespace>DevWinUI</BaseNamespace>
    <SourceGeneratorLibName>DevWinUI.SourceGenerator</SourceGeneratorLibName>
    <ShaderLibName>DevWinUI.Shader</ShaderLibName>
    
    <!-- Major Version -->
    <LibraryMajorVersion>10</LibraryMajorVersion>

    <!-- Minor Version -->
    <DevWinUI_MinorVersion>4</DevWinUI_MinorVersion>
    <DevWinUI_Base_MinorVersion>4</DevWinUI_Base_MinorVersion>
    <DevWinUI_ContextMenu_MinorVersion>0</DevWinUI_ContextMenu_MinorVersion>
    <DevWinUI_SourceGenerator_MinorVersion>2</DevWinUI_SourceGenerator_MinorVersion>
    <DevWinUI_Shader_MinorVersion>1</DevWinUI_Shader_MinorVersion>
    <DevWinUI_Gallery_MinorVersion>4</DevWinUI_Gallery_MinorVersion>

    <!-- Patch Version -->
    <DevWinUI_PatchVersion>0</DevWinUI_PatchVersion>
    <DevWinUI_Base_PatchVersion>0</DevWinUI_Base_PatchVersion>
    <DevWinUI_ContextMenu_PatchVersion>0</DevWinUI_ContextMenu_PatchVersion>
    <DevWinUI_SourceGenerator_PatchVersion>0</DevWinUI_SourceGenerator_PatchVersion>
    <DevWinUI_Shader_PatchVersion>0</DevWinUI_Shader_PatchVersion>
    <DevWinUI_Gallery_PatchVersion>0</DevWinUI_Gallery_PatchVersion>
    
    <!-- -Preview -->
    <IsPreviewBuild>false</IsPreviewBuild>
    <PreviewLabel>-Preview1</PreviewLabel>
    <PreviewBuildSuffix Condition="'$(IsPreviewBuild)' == 'true'">$(PreviewLabel)</PreviewBuildSuffix>
    
    <!-- The NuGet package version -->
    <XAMLToolsVersion>1.0.0-alpha.189</XAMLToolsVersion>
    <CsWin32Version>0.3.321</CsWin32Version>
    <Win2dVersion>1.4.0</Win2dVersion>
    <ComputeSharpVersion>3.2.0</ComputeSharpVersion>
    <WASDKWinUIVersion>2.3.6</WASDKWinUIVersion>

    <NoWarn>CS8632;WIN2D0001;WMC1510;WMC0001</NoWarn>

    <OutputPath Condition="'$(MSBuildProjectName)' != $(GalleryAppName)">$(SolutionDir)Output\</OutputPath>
    
    <RootNamespace>$(BaseNamespace)</RootNamespace>
    
    <ImplicitUsings>true</ImplicitUsings>
    <LangVersion>Latest</LangVersion>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
    <CsWinRTAotWarningLevel Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">2</CsWinRTAotWarningLevel>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    
    <!-- The NuGet package options -->
    <PackageIcon>Icon.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>Mahdi Hosseini</Authors>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild Condition="'$(Configuration)' != 'Debug' And '$(MSBuildProjectName)' != $(GalleryAppName)">True</GeneratePackageOnBuild>
    <Copyright>Copyright (c) 2021-$([System.DateTime]::Now.Year) - Mahdi Hosseini</Copyright>
    <PackageProjectUrl>https://github.com/ghost1372/DevWinUI</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ghost1372/DevWinUI</RepositoryUrl>
    <PackageReleaseNotes>https://github.com/ghost1372/DevWinUI/releases</PackageReleaseNotes>
  </PropertyGroup>
  
  <PropertyGroup Condition="$(MSBuildProjectName) != $(SourceGeneratorLibName) ">
    
    <!-- TargetFramework version -->
    <DebugTargetFramework>net10.0-windows10.0.19041.0</DebugTargetFramework>
    <DebugShaderAndGalleryTargetFramework>net10.0-windows10.0.26100.0</DebugShaderAndGalleryTargetFramework>

    <GalleryTargetFramework>$(DebugShaderAndGalleryTargetFramework)</GalleryTargetFramework>

    <TargetFrameworks Condition=" '$(Configuration)' == 'Release' And $(MSBuildProjectName) != $(GalleryAppName) ">$(DebugTargetFramework)</TargetFrameworks>
    <TargetFrameworks Condition=" '$(Configuration)' == 'Debug' And $(MSBuildProjectName) != $(GalleryAppName)">$(DebugTargetFramework)</TargetFrameworks>

    <TargetFrameworks Condition=" '$(Configuration)' == 'Release' And $(MSBuildProjectName) == $(ShaderLibName) ">$(DebugShaderAndGalleryTargetFramework)</TargetFrameworks>
    <TargetFrameworks Condition=" '$(Configuration)' == 'Debug' And $(MSBuildProjectName) == $(ShaderLibName)">$(DebugShaderAndGalleryTargetFramework)</TargetFrameworks>

    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI Condition="'$(MSBuildProjectName)' != $(ContextMenuLibName)">true</UseWinUI>
    <WinUISDKReferences Condition="'$(MSBuildProjectName)' != $(ContextMenuLibName)">false</WinUISDKReferences>

  </PropertyGroup>

  <!-- The NuGet versions of dependencies to build against. -->
  <ItemGroup Condition="'$(MSBuildProjectName)' != $(ContextMenuLibName) And '$(MSBuildProjectName)' != $(SourceGeneratorLibName) And '$(MSBuildProjectName)' != $(GalleryAppName)">
    <PackageReference Include="Microsoft.WindowsAppSDK.WinUI" Version="$(WASDKWinUIVersion)" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(MSBuildProjectName)' != $(GalleryAppName)">
    <None Include="..\..\tools\Assets\DevWinUI.png" Pack="true" PackagePath="Icon.png" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
  <Target Name="GetVersion">
    <Message Text="$(Version)" Importance="High" />
  </Target>
</Project>
