<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>$(LibraryMajorVersion).$(DevWinUI_MinorVersion).$(DevWinUI_PatchVersion)$(PreviewBuildSuffix)</Version>
    <PackageId>$(BaseNamespace)</PackageId>
    <AssemblyName>$(BaseNamespace)</AssemblyName>
    <Description>
      Experience WinUI 3 quickly and easily with the help of DevWinUI, Everything you need to develop an application is gathered in one place. DevWinUI Includes custom controls, styles, landingPages,Compositions and win2d.
    </Description>
    <PackageTags>winui winui3 win11 xaml DevWinUI DevWinUI.Controls SettingsUI Components settings theme styles projectreunion winappsdk windowsappsdk wasdk reunion SettingsControls settingsexpander settingscard landingPages win2d composition</PackageTags>
    <!-- Remove trailing .0 from Windows TFM -->
    <CleanTargetFramework>$([System.Text.RegularExpressions.Regex]::Replace('$(TargetFramework)','\.0$',''))</CleanTargetFramework>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackCustomContent</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Graphics.Win2D" Version="$(Win2dVersion)" />
    <PackageReference Include="XAMLTools.MSBuild" Version="$(XAMLToolsVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.WinUI.Animations" Version="8.3.260402-preview2" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.3.260402-preview2" />
    <PackageReference Include="CommunityToolkit.WinUI.Media" Version="8.3.260402-preview2" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.1" />
  </ItemGroup>
  <ItemGroup>
    <XAMLCombineItems Include="Themes\Styles\**\*.xaml">
      <TargetFile>Themes\Generic.xaml</TargetFile>
      <Visible>True</Visible>
    </XAMLCombineItems>
    <XAMLCombineItems Include="Controls\Ported\**\*.xaml" Exclude="Controls\Ported\Sidebar\SidebarView.xaml;Controls\Ported\StoreCarousel2\ScreenshotsViewer.xaml;Controls\Ported\StoreCarousel2\PreviewViewer.xaml;Controls\Ported\StoreCarousel2\PreviewViewerScreenshotItem.xaml;Controls\Ported\StoreCarousel2\PreviewViewerVideoItem.xaml">
      <TargetFile>Themes\Generic.xaml</TargetFile>
      <Visible>True</Visible>
    </XAMLCombineItems>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\tools\Assets\Mask\ForegroundFocusMask.png">
      <LogicalName>Assets.Mask.ForegroundFocusMask.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\tools\Assets\Mask\TextGlitchMask.png">
      <LogicalName>Assets.Mask.TextGlitchMask.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\tools\Assets\Mask\CircleMask.png">
      <LogicalName>Assets.Mask.CircleMask.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\tools\Assets\Noise\Noise.jpg">
      <LogicalName>Assets.Noise.Noise.jpg</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DevWinUI.Base\DevWinUI.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build\$(PackageId).targets" Pack="true" PackagePath="build\" />
  </ItemGroup>
  
  <Target Name="PackCustomContent">
    <ItemGroup>
      <TfmSpecificPackageFile Include="Themes\Generic.xaml">
        <PackagePath>lib\$(CleanTargetFramework)\DevWinUI\Themes\</PackagePath>
      </TfmSpecificPackageFile>
    </ItemGroup>
  </Target>
</Project>